---
- name: Add PowerDNS APT key
  apt_key:
    url: https://repo.powerdns.com/FD380FBB-pub.asc

- name: Add the PowerDNS Authoritative Apt repository
  apt_repository:
    repo: deb http://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}-auth-{{ pdns_auth_repo_ver }} main
    filename: pdns-authoritative
    update_cache: true

- name: Pin pdns packages
  copy:
    dest: /etc/apt/preferences.d/pdns
    content: >
      Package: pdns-*
      Pin: origin repo.powerdns.com
      Pin-Priority: 600
    mode: 0644
    owner: root
    group: root

- name: Install the PowerDNS Authoritative server packages
  apt:
    name:
      - pdns-server
      - pdns-backend-pgsql
      - dnsutils

- include_tasks: database.yml
  when: pdns_auth_configure_postgres

- name: Create configuration file
  template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    mode: 0640
    owner: pdns
  notify: Restart PowerDNS

- name: Create PowerDNS override directory
  file:
    path: /etc/systemd/system/pdns.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  when: pdns_auth_config.chroot is defined

- name: Create PowerDNS override file
  template:
    src: pdns-chroot-resolv.conf.j2
    dest: /etc/systemd/system/pdns.service.d/chroot-resolv.conf
    owner: root
    group: root
    mode: 0644
  when: pdns_auth_config.chroot is defined

- name: Remove PowerDNS override file
  file:
    path: /etc/systemd/system/pdns.service.d/chroot-resolv.conf
    state: absent
  when: pdns_auth_config.chroot is not defined

- name: Enable PowerDNS
  service:
    name: pdns.service
    enabled: yes

- name: Start PowerDNS
  systemd:
    daemon_reload: yes
    name: pdns.service
    state: started
  register: pdns_start
